org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17.21
fabric_api_version=0.161.0+26.3
adventure_platform_version=7.2.0
jedis_version=7.1.0

mod_version=0.7.1+26.3
maven_group=dev.crossserverchat
archives_base_name=CrossServerChat
